version: '3.5'

services:
    ocrwatch:
        build: .
        environment:
            # obscure password with rclone obscure PASSWORD
            - WOCR_CMD=ocrmypdf -l eng+deu --rotate-pages --jobs 2 --output-type pdfa %INFILE% %OUTFILE%
            - WOCR_AFTERCMD=mv %FILE% /output
        volumes:
          - type: bind
            source: ./in
            target: /consume
          - type: bind
            source: ./out
            target: /output

