version: '3.5'

services:
    ocrwatch:
        build: .
        volumes:
            - /consume/shared:/consume
        environment:
# obscure password with rclone obscure PASSWORD
            - OCRWATCH_AFTER=rclone copy --webdav-url https://NEXTCLOUD_URL/remote.php/webdav/ --webdav-user NEXTCLOUD_USER --webdav-pass NEXTCLOUD_PASS_OBSCURED  %FILE% :webdav:/OCR
            - OCRWATCH_OCRMYPDF=-l eng+deu --rotate-pages --deskew --clean --remove-background --jobs 2 --output-type pdfa --jbig2-lossy --optimize 3